### ISSUE TITLE
Params "fill" doesn't work

### ISSUE THREAD

**Issue by Xtron33** [gravity-ui/icons#47]
I want to recolor icon to white color, but this code doen't work

`<Icon size={20} fill={"white"} data={Person}/>`

Cause this parameter set fill in wrong place. I copy this from devtools:

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="20" height="20" class="yc-icon" fill="white" stroke="none" aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 16"><path fill="currentColor" fill-rule="evenodd" d="M10 4.5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm1.5 0a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm-9 8c0-.204.22-.809 1.32-1.459C4.838 10.44 6.32 10 8 10c1.68 0 3.162.44 4.18 1.041 1.1.65 1.32 1.255 1.32 1.459a1 1 0 0 1-1 1h-9a1 1 0 0 1-1-1Zm5.5-4c-3.85 0-7 2-7 4A2.5 2.5 0 0 0 3.5 15h9a2.5 2.5 0 0 0 2.5-2.5c0-2-3.15-4-7-4Z" clip-rule="evenodd"></path></svg></svg>`

How can you see "white" stay in wrong place, cause currentColor stay static.

I know what I can fix it using themeprovider, but I needn't theme provider in this project.

**Comment by amje** [comment]
@Xtron33 You can set whatever color you want using using the CSS `color` property:
```jsx
.my-icon {
  color: white;
}

<Icon className="my-icon"/>
```

**Comment by Xtron33** [comment]
@amje 
Yes, in my project I fixed it with css but cause Icon component have more difficult structure its fixing more difficult code.

`&__item-icon{
      svg{
        path{
          fill: white;
        }
      }
    }`
    
However, I opened this Issue just for in future this bug will be fix.

**Comment by amje** [comment]
Please reopen the issue if it's still relevant
